version: '3'

services:
  quick-statement-api:
    container_name: quick-statement-api
    build:
      context: .
      args:
        - buildwith=production
        - buildwithout=development,test
    entrypoint: /project/.docker_boot_production.sh
    links:
      - quick-statement-mongo
    volumes:
      - .:/project

  quick-statement-mongo:
    container_name: quick-statement-mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: quick_statement
    volumes:
      - quick-statement-mongo-data:/data/db

  quick-statement-mongo-express:
    container_name: quick-statement-mongo-express
    image: mongo-express
    ports:
      - 8081:8081
    links:
      - quick-statement-mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: quick-statement-mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin

volumes:
  quick-statement-mongo-data:
    driver: local
