version: '3'

services:
  quick-statement-api:
    entrypoint: /project/.docker_boot_development.sh
    ports:
      - 0.0.0.0:8000:4000
    stdin_open: true
    tty: true

  quick-statement-mongo-express:
    container_name: quick-statement-mongo-express
    image: mongo-express
    ports:
      - 8081:8081
    links:
      - quick-statement-mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: quick-statement-mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    networks:
      - quick-statement-app_quick-statement-net
